In [2]:
import os
import glob
import pandas as pd
import numpy as np
import json

In [8]:
os.getcwd()

'/home/spai0722'

In [96]:
base_dir = "Bidcoin"  # Bidcoin 폴더 경로 (상대/절대 경로로 수정 가능)

# Bidcoin 폴더 안의 json 파일 목록 가져오기
json_paths = glob.glob(os.path.join(base_dir, "*.json"))

dfs = dict() # category별 RAGAS 점수
for path in json_paths:
    df = pd.read_json(path)
    category = df['category'].iloc[0]
    ragas = pd.DataFrame([i for i in df['evaluation']]).fillna(0).mean().to_dict()
    dfs[category] = ragas

In [102]:
a = pd.read_json(r"/home/spai0722/Bidcoin/eval_results_20260417_020440.json")

In [103]:
a

,id,category,query,example_answer,answer,evaluation
0,fact_01,fact,국민연금공단 2024년 이러닝시스템 운영 용역의 예산은 얼마야?,"773,801,000원 (약 7억 7,380만 원)","1. 답변: 예산은 총 773,801천원(약 7.73801억원)입니다.\n\n2. ...","{'faithfulness': None, 'answer_relevancy': 0.3..."
1,fact_02,fact,고려대학교 차세대 포털·학사 정보시스템 구축사업의 발주기관과 사업 금액을 알려줘.,"발주기관: 고려대학교, 사업 금액: 11,270,000,000원 (약 112억 7천...","1. 답변: 발주기관은 고려대학교이며, 사업금액은 112.7억원(11,270,000...","{'faithfulness': None, 'answer_relevancy': 0.3..."
2,fact_03,fact,스포츠윤리센터 LMS 기능개선 사업의 입찰 참여 마감일은 언제야?,2024년 9월 2일,1. 답변: 스포츠윤리센터 LMS 기능개선 사업의 입찰 마감일은 2024년 9월 2...,"{'faithfulness': 1.0, 'answer_relevancy': 0.96..."
3,fact_04,fact,"한국연구재단 UICC 기능개선 사업의 공개 일자, 입찰 시작일, 마감일을 알려줘.","공개 일자: 2024년 10월 4일, 입찰 시작일: 2024년 10월 14일, 마감...","1. 답변: 입찰 마감일은 2024년 10월 16일이며, 공개 일자와 입찰 시작일은...","{'faithfulness': None, 'answer_relevancy': 0.2..."
4,fact_05,fact,광주과학기술원 학사시스템 기능개선 사업 예산 얼마야?,"157,300,000원 (약 1억 5,730만 원)","1. 답변: 광주과학기술원 학사시스템 기능개선 사업 예산은 157,300,000원(...","{'faithfulness': None, 'answer_relevancy': 0.5..."
5,fact_06,fact,국민연금공단 이러닝 용역 입찰 참여 시작일은?,2024년 2월 21일,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'faithfulness': 0.75, 'answer_relevancy': 0.3..."
6,fact_07,fact,스포츠윤리센터 LMS 기능개선 사업의 발주기관이 어디야?,재단법인스포츠윤리센터,"1. 답변: 발주기관은 재단법인스포츠윤리센터입니다.\n2. 근거: ""발주기관: 재단...","{'faithfulness': 0.6666666666666661, 'answer_r..."
7,condition_01,condition,국민연금공단 2024년 이러닝시스템 운영 용역에 유지보수 포함돼?,포함됨. 사업 범위에 이러닝시스템 운영 및 콘텐츠 관리 업무가 명시되어 운영지원 요...,1. 확인 결과: 있음.\n\n2. 세부 내용:\n- 문서별 근거\n - 문서 1...,"{'faithfulness': None, 'answer_relevancy': 0.2..."
8,condition_02,condition,고려대학교 차세대 포털·학사 정보시스템 구축사업에 응답속도나 성능 요구사항 있어?,있음. 사용자 정보서비스 접근성 개선 및 시스템 안정성 관련 성능 요건이 포함되어 있다.,"1. 확인 결과: 있음.\n\n2. 세부 내용: 문서에 ""성능요구사항"" 항목이 있고...","{'faithfulness': None, 'answer_relevancy': 0.3..."
9,condition_03,condition,"국민연금공단 이러닝 용역이 구축 사업이야, 운영 사업이야?","운영 사업. 이러닝시스템 운영 및 콘텐츠 관리 중심이며, 신규 구축이 아닌 운영·용...","1. 답변: 운영 용역이지만 구축 업무도 포함되어 있습니다. \n2. 근거: ""2...","{'faithfulness': None, 'answer_relevancy': 0.5..."
10,condition_04,condition,광주과학기술원 학사시스템 기능개선 사업에서 시스템 연계 요구 있어?,있음. 학사 조직개편에 따른 시스템 개선 및 학위 연계과정 시스템 구축이 사업 범위...,1. 확인 결과: 있음.\n\n문서별 관련 내용\n- 문서 1: 시스템 연계를 위한...,"{'faithfulness': None, 'answer_relevancy': 0.3..."
11,condition_05,condition,한국연구재단 UICC 기능개선 사업에 운영 인력 요구 있어?,있음. UICC 시스템 운영 지원을 통한 안정적인 실태조사 추진이 명시되어 있어 운...,1. 확인 결과: 있음\n\n2. 세부 내용:\n- 문서별 관련 내용 정리:\n ...,"{'faithfulness': None, 'answer_relevancy': 0.2..."
12,summary_01,summary,국민연금공단 2024년 이러닝시스템 운영 용역의 목적과 주요 업무를 5줄 이내로 정...,"비대면 교육수요 증가·직원 역량 강화 필요성을 배경으로, 교육과정 운영·이러닝시스템...",1. 요약: 이 사업의 목적은 안정적인 학습관리시스템(LMS) 기반의 상시·맞춤형 ...,"{'faithfulness': None, 'answer_relevancy': 0.2..."
13,summary_02,summary,고려대학교 차세대 포털·학사 정보시스템 구축사업의 추진 배경과 핵심 구축 목표를 요...,"학령인구 감소·급격한 사회기술 변화에 대응하여 분산된 시스템과 데이터를 통합하고, ...",추진 배경은 노후·분산된 학사·포털 시스템으로 인한 정보접근성·행정비효율·의사결정 ...,"{'faithfulness': None, 'answer_relevancy': 0.6..."
14,summary_03,summary,광주과학기술원 학사시스템 기능개선 사업의 목적을 요약해줘.,학사 업무 편리성 제고·업무 효율성 극대화·사용자 편의성 증대를 목적으로 학사 조직...,1. 요약: 본 사업의 목적은 GIST의 학사조직 개편 및 학위 과정 변경에 따라 ...,"{'faithfulness': None, 'answer_relevancy': 0.3..."
15,summary_04,summary,한국연구재단 UICC 기능개선 사업이 왜 추진되는 거야?,대학 산학협력활동 실태조사를 안정적으로 운영하고 사용자 편의성을 개선하기 위해 UI...,1. 답변: 한국연구재단 UICC 기능개선 사업은 실태조사 시스템의 안정적 운영과 ...,"{'faithfulness': None, 'answer_relevancy': 0.8..."
16,compare_01,compare,고려대학교 차세대 포털·학사 정보시스템 구축사업과 광주과학기술원 학사시스템 기능개선...,고려대학교: 학령인구 감소 대응·시스템 전면 통합 재구축 (112억 7천만 원). ...,결론: 광주과학기술원(GIST) 학사시스템 기능개선 사업의 목적·범위는 제공된 문서...,"{'faithfulness': None, 'answer_relevancy': 0.7..."
17,compare_02,compare,국민연금공단 이러닝 용역과 스포츠윤리센터 LMS 기능개선 사업의 성격 차이를 비교해줘.,국민연금공단: 직원 역량 강화 목적 이러닝 플랫폼 운영 용역 (7억 7천만 원). ...,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'faithfulness': None, 'answer_relevancy': 0.0..."
18,compare_03,compare,교육 또는 학습 관련 사업들 중 예산 규모가 더 큰 쪽은 어디야?,"고려대학교 차세대 포털·학사 정보시스템 구축사업 (11,270,000,000원)이 ...",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'faithfulness': 0.0, 'answer_relevancy': 0.0,..."
19,compare_04,compare,학사 시스템 관련 사업들만 묶어서 차이점을 설명해줘.,"고려대학교 (112억, 전면 통합 재구축), 광주과학기술원 (1억 5,730만, 조...",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'faithfulness': 0.0, 'answer_relevancy': 0.0,..."
20,recommend_01,recommend,교육 콘텐츠 구축 경험이 많은 고객사에게 추천할 만한 공고 있어?,국민연금공단 이러닝시스템 운영 용역 (콘텐츠 개발·관리 포함)과 스포츠윤리센터 LM...,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제출된 ...,"{'faithfulness': 0.0, 'answer_relevancy': 0.15..."
21,recommend_02,recommend,대학 정보시스템 구축 경험이 있는 업체에 적합한 공고를 찾아줘.,고려대학교 차세대 포털·학사 정보시스템 구축사업 (대규모 포털·학사 통합 구축)과 ...,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 검색된 ...,"{'faithfulness': 0.0, 'answer_relevancy': 0.0,..."
22,recommend_03,recommend,예산 5억 이상인 사업만 추려줘.,"고려대학교 차세대 포털·학사 정보시스템 구축사업 (112억 7천만 원), 국민연금공...",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'faithfulness': 0.0, 'answer_relevancy': 0.12..."
23,follow_up_01,follow_up,국민연금공단 이러닝 용역에서 콘텐츠 관리 요구만 더 자세히 보여줘.,콘텐츠 개발·관리 업무로 이러닝 콘텐츠 신규 개발 및 기존 콘텐츠 유지관리가 사업 ...,"요약: 문서들에서 확인되는 국민연금공단 이러닝 용역의 콘텐츠 관리 요구는 ""콘텐츠 ...","{'faithfulness': None, 'answer_relevancy': 0.2..."
24,follow_up_02,follow_up,고려대학교 차세대 포털·학사 정보시스템 구축사업 일정 정보만 알려줘.,"입찰 참여 시작일: 2024년 7월 5일, 마감일: 2024년 8월 12일","1. 답변: 입찰마감일은 2024년 8월 12일이며, 사업기간은 계약일로부터 24개...","{'faithfulness': None, 'answer_relevancy': 0.1..."
25,follow_up_03,follow_up,"광주과학기술원 학사시스템 기능개선 사업, 구축이야 운영이야?",기능개선(부분 구축) 성격. 신규 전면 구축이 아니라 기존 학사시스템의 조직개편 반...,1. 답변: 광주과학기술원 학사시스템 기능개선 사업은 주로 시스템 구축(개발 및 설...,"{'faithfulness': None, 'answer_relevancy': 0.5..."
26,refusal_01,refusal,삼성전자가 발주한 RFP가 이 데이터셋에 있는지 확인해줘.,데이터셋에 삼성전자가 발주한 RFP는 존재하지 않습니다.,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'faithfulness': None, 'answer_relevancy': 0.0..."
27,refusal_02,refusal,국민연금공단 이러닝 용역에서 AWS 사용이 필수인지 알려줘. 문서에 없으면 없다고 해줘.,문서에 AWS 사용 의무화에 관한 내용이 없습니다.,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'faithfulness': None, 'answer_relevancy': 0.0..."
28,refusal_03,refusal,고려대학교 차세대 포털 사업 문서에 투입 개발자 수가 명시돼 있어?,문서에 투입 개발자 수에 대한 구체적 명시가 없습니다.,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'faithfulness': None, 'answer_relevancy': 0.0..."
29,evidence_01,evidence,국민연금공단 이러닝 용역에서 주요 업무 범위를 보여주는 근거 문장을 출처와 함께 제...,"""사업범위: 교육과정 운영, 이러닝시스템 운영, 콘텐츠 개발·관리"" (출처: 국민연...",1. 답변: 국민연금공단 이러닝 용역의 주요 업무 범위는 교육운영(프로그램·콘텐츠 ...,"{'faithfulness': None, 'answer_relevancy': 0.8..."
30,evidence_02,evidence,고려대학교 차세대 포털·학사 정보시스템 구축사업에서 구축 목표를 보여주는 근거 문장...,"""차세대 구축을 통해 정보서비스 품질 강화 및 대학 교육 시스템 경쟁력 확보"" (출...","1. 종합 요약: 차세대 포털·학사 정보시스템 구축의 핵심 목표는 ""노후화된 시스템...","{'faithfulness': None, 'answer_relevancy': 0.4..."
31,evidence_03,evidence,한국연구재단 UICC 기능개선 사업에서 추진 배경을 보여주는 근거 문장을 제시해줘.,"""대학 산학협력활동 실태조사를 안정적으로 운영하고 사용자 편의성을 개선하기 위해 필...","1. 답변: 추진 배경을 보여주는 근거 문장은 ""한국연구재단법 제5조, 산업교육진흥...","{'faithfulness': 0.6666666666666661, 'answer_r..."
32,complex_01,complex,"국민연금공단 2024년 이러닝시스템 운영 용역에 대해 목적, 주요 업무, 운영 범위...",목적: 직원 역량 강화·상시 학습 활성화. 주요 업무: 교육과정 운영·이러닝시스템 ...,"결론: 아래에 문서별로 목적·주요업무·운영범위·유지보수 요구·일정을 정리하고, 마지...","{'faithfulness': None, 'answer_relevancy': 0.8..."
33,complex_02,complex,고려대학교 차세대 포털·학사 시스템 사업과 광주과학기술원 학사시스템 기능개선 사업을...,"고려대학교: 목적=시스템 통합·접근성 개선, 범위=전면 재구축, 예산=112억 7천...","해당 정보를 문서에서 확인할 수 없습니다.\n\n이유: 제공된 문서들은 모두 ""고려...","{'faithfulness': None, 'answer_relevancy': 0.0..."

In [104]:
pd.DataFrame([i for i in a['evaluation']]).fillna(0).mean().to_dict()

{'faithfulness': 0.09068627450980389,
 'answer_relevancy': 0.3467995675855641,
 'context_precision': 0.6582107842931402,
 'context_recall': 0.5098039215686274,
 'answer_correctness': 0.06502161281431452}

In [97]:
dfs

{'fact': {'faithfulness': 0.07843137254901959,
  'answer_relevancy': 0.3946598984970646,
  'context_precision': 0.6129493463860297,
  'context_recall': 0.49509803921568624,
  'answer_correctness': 0.001442400624286706}}

In [93]:
df_final = pd.DataFrame(dfs)
df_final

                        fact
faithfulness        0.078431
answer_relevancy    0.394660
context_precision   0.612949
context_recall      0.495098
answer_correctness  0.001442

In [33]:
df_final.T.sort_values(by='faithfulness', ascending=False)

,faithfulness,answer_relevancy,context_precision,context_recall,answer_correctness
fact,0.900000,0.344709,0.857143,0.761905,0.481715
condition,0.760000,0.319889,1.000000,0.500000,0.333944
evidence,0.611111,0.512512,0.944444,1.000000,0.191714
follow_up,0.600000,0.143635,1.000000,0.833333,0.112767
summary,0.500000,0.615186,1.000000,1.000000,0.514673
compare,0.468750,0.000000,0.395833,0.250000,0.039719
refusal,0.166667,0.000000,0.000000,0.333333,0.292528
recommend,0.000000,0.000000,0.000000,0.222222,0.140596
complex,0.000000,0.000000,1.000000,0.750000,0.000000

In [43]:
df_final.to_csv("ragas_scores_by_category.csv", index=False)

In [88]:
df_final.T

,faithfulness,answer_relevancy,context_precision,context_recall,answer_correctness
condition,0.760000,0.319889,1.000000,0.500000,0.333944
recommend,0.000000,0.000000,0.000000,0.222222,0.140596
follow_up,0.600000,0.143635,1.000000,0.833333,0.112767
summary,0.500000,0.615186,1.000000,1.000000,0.514673
compare,0.468750,0.000000,0.395833,0.250000,0.039719
refusal,0.166667,0.000000,0.000000,0.333333,0.292528
complex,0.000000,0.000000,1.000000,0.750000,0.000000
fact,0.900000,0.344709,0.857143,0.761905,0.481715
evidence,0.611111,0.512512,0.944444,1.000000,0.191714

In [90]:
df_final.T.mean()

faithfulness          0.445170
answer_relevancy      0.215103
context_precision     0.688602
context_recall        0.627866
answer_correctness    0.234184
dtype: float64

In [3]:
df_a = pd.read_json(r"/home/spai0722/Bidcoin/eval_results_20260419_134319.json")
df_a

,id,category,query,example_answer,answer,evaluation
0,Q01,금액,고려대학교 차세대 포털·학사 정보시스템 구축사업의 사업 금액은 얼마인가?,"112억 7천만 원 (11,270,000,000원)","1. 답변: 사업 금액은 11,270,000,000원(부가세 포함, 문서에는 별도로...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
1,Q02,금액,봉화군 재난통합관리시스템 고도화 사업의 예산은?,"9억 원 (900,000,000원)","1. 답변: 봉화군 재난통합관리시스템 고도화 사업의 예산은 900,000,000원(...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
2,Q03,금액,한영대학교 학사정보시스템 고도화 사업의 예산은 얼마인가?,"1억 3천만 원 (130,000,000원)","1. 답변: 예산은 총 ₩130,000,000원(부가세 포함)입니다.\n\n2. 근...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
3,Q04,금액,전기안전 관제시스템 보안 모듈 개발 용역의 사업 금액은?,"222,180,200원","1. 답변: 사업 금액은 ₩220,000,000(VAT 포함)입니다. (문서 일부 ...","{'relevance': 0.75, 'faithfulness': 0.75, 'cor..."
4,Q05,금액,인천광역시 도시계획위원회 통합관리시스템 구축용역 예산은?,"1억 5천만 원 (150,000,000원)","1. 답변: 예산은 150,000,000원(1.5억원)입니다.\n2. 근거: ""[발...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
5,Q06,기관,학사 정보시스템 구축 사업을 2024년에 가장 큰 예산으로 발주한 기관은?,"고려대학교 (차세대 포털·학사 정보시스템, 약 112억 원)",1. 답변: 2024년에 학사 정보시스템 구축 사업을 가장 큰 예산으로 발주한 기관...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
6,Q07,기관,UICC 기능개선 사업을 발주한 기관은 어디인가?,한국연구재단,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 검색된 ...,"{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."
7,Q08,기관,GIS 통계 기반 재난안전데이터 분석 시스템을 구축하는 기관은?,재단법인충북연구원,1. 답변: GIS/통계 기반 재난안전데이터 분석·관리 시스템을 구축하는 기관은 재...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
8,Q09,기관,대용량 자료전송시스템 고도화 사업을 발주한 기관은?,국방과학연구소,"1. 답변: 해당 사업의 발주기관은 국방과학연구소입니다.\n2. 근거: ""[발주기관...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
9,Q10,기관,KUSF 체육특기자 경기기록 관리시스템 개발을 발주한 기관은?,(사)한국대학스포츠협의회,1. 답변: KUSF 체육특기자 경기기록 관리시스템 개발을 발주한 기관은 (사)한국...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
10,Q11,기간,한국연구재단의 UICC 기능개선 사업 기간이 어떻게 되는가?,계약일로부터 210일,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'relevance': 0.0, 'faithfulness': 1.0, 'corre..."
11,Q12,기간,전기안전 관제시스템 보안 모듈 개발 용역 사업 기간이 어떻게 되는가?,계약 후 180일,"1. 답변: 사업 기간은 계약 체결일로부터 180일입니다. \n2. 근거: ""사업...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
12,Q13,기간,봉화군 재난통합관리시스템 사업 기간이 어떻게 되는가?,착수일로부터 7개월(210일),"1. 답변: 사업 기간은 계약(착수) 후 210일, 즉 7개월입니다. \n2. 근...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
13,Q14,사업내용,한영대학교 트랙운영 학사정보시스템 고도화 사업의 주요 목적은 무엇인가?,"트랙제 교육과정 도입 및 운영 관리 체계 구축, 학사운영 시스템 고도화",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'relevance': 0.0, 'faithfulness': 1.0, 'corre..."
14,Q15,복합,EIP3.0 고압가스 안전관리 시스템 구축 용역의 발주 기관과 예산은?,"한국생산기술연구원, 4천만 원 (40,000,000원)","1. 답변: 발주 기관은 한국생산기술연구원이며, 예산은 4천만원입니다. \n2. ...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
15,Q16,복합,수도국산달동네박물관 사업의 예산은?,"200,000,000원(금200,000천원)",해당 정보를 문서에서 확인할 수 없습니다. \n이유: 제공된 문서가 전혀 검색되지...,"{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."
16,Q17,금액,벤처확인종합관리시스템 사업 금액은?,"3억 5,200만 원 (352,000,000원)","1. 답변: 사업금액은 352,000,000원입니다.\n\n2. 근거: ""[발주기관...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
17,Q18,금액,국방과학연구소의 대용량 자료전송시스템 고도화 예산은?,"316,800,000원","1. 답변: 국방과학연구소의 '대용량 자료전송시스템 고도화' 예산은 316,800,...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
18,Q19,금액,GIS 통계 기반 재난안전데이터 분석 시스템 예산은 얼마인가?,"1억 원 (100,000,000원)","1. 답변: 예산은 ₩100,000,000입니다.\n\n2. 근거:\n- ""[발주기...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
19,Q20,금액,평택시 버스정보시스템 사업의 예산은?,"999,494,600원","1. 답변: 평택시 버스정보시스템(BIS) 구축사업의 예산은 ₩999,494,600...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
20,Q21,추천,봉화군 재난통합관리시스템 고도화 사업에 참가해야 할지 판단해줘. 우리는 재난관리 S...,자격 요건·예산(9억)·납기 일정을 문서에서 확인 후 적합 여부 판단 필요; 실적 ...,참가 적합성은 제공된 문서만으로는 확정할 수 없습니다. (문서에 명시 없음)\n\n...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
21,Q22,추천,고려대학교 차세대 포털·학사 정보시스템 구축사업 참가 적합성을 항목별로 점수화해서 ...,참가 자격·기술 요구사항·예산(112억)·납기·실적 요건·공동수급 허용 여부를 각각...,1. 종합 판정: 조건부 GO — 문서에 명시된 기술·일정·예산 요건에 대한 정보는...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
22,Q23,추천,"한영대학교 학사정보시스템 고도화 사업을 검토 중인데, 우리 회사는 공공 SW 납품 ...",공공 실적 요건 미충족 가능성 높아 추천하지 않음; 문서상 자격요건 재확인 후 결격...,1. 판정: 추천하지 않습니다. 핵심 사유는 제안 참가 자격으로서 최근 3년 이내에...,"{'relevance': 1.0, 'faithfulness': 0.75, 'corr..."
23,Q24,비교,봉화군 재난통합관리시스템 사업과 인천광역시 도시계획위원회 통합관리시스템 구축용역을 ...,"봉화군: 9억 원, 재난통합관리 / 인천광역시: 1.5억 원, 도시계획위원회 통합관...",해당 질문은 제공된 RFP 문서 범위를 벗어납니다. 제공된 문서들은 모두 인천광역시...,"{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."
24,Q25,비교,"고려대학교 포털 사업, 한영대학교 학사시스템, 한국사학진흥재단 대학재정정보시스템 세...",고려대 112억 / 한영대 1.3억 / 한국사학진흥재단 2.1억; 목적·발주기관·요...,결론: 제공된 문서들에서 상세하게 확인 가능한 사업은 '한국사학진흥재단 대학재정정보...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
25,Q26,비교,"봉화군 재난통합관리시스템과 GIS 통계 기반 재난안전데이터 분석 시스템, 두 사업의...",각 사업의 보안 요구사항은 해당 RFP 문서에서 개별 확인 필요; 공통 보안 항목 ...,결론: 봉화군 재난통합관리시스템의 보안 요구사항은 상세하게 항목화(SER-01~SE...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
26,Q27,확인불가,고려대학교 차세대 포털 사업의 우선협상 대상자는 누구인가?,해당 정보를 문서에서 확인할 수 없습니다. (낙찰·협상 결과는 RFP 문서 범위 외),1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
27,Q28,확인불가,한국연구재단 UICC 기능개선 사업의 예산과 납품 후 하자보수 기간은?,예산은 문서에서 확인 가능; 하자보수 기간은 해당 문서에 명시되어 있지 않음,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'relevance': 0.25, 'faithfulness': 0.0, 'corr..."
28,Q29,확인불가,공공조달 입찰에서 일반적으로 낙찰 성공률을 높이는 방법은 무엇인가요?,해당 질문은 제공된 RFP 문서의 범위를 벗어납니다. 일반 지식 기반 답변은 제공하...,추천: 문서에 명시된 준수·제출 요건과 평가 절차를 충실히 따르면 낙찰 성공률을 높...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
29,Q30,후속,"방금 설명한 고려대 포털 사업 예산에서, 부가세 포함 여부도 확인할 수 있어?","부가세(V.A.T) 포함 금액으로 문서에 명시됨 — '(V.A.T 포함, 3년 분할...",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n2. 이유: 제공된 ...,"{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."
30,Q31,후속,아까 설명한 봉화군 재난통합관리시스템 사업의 주요 요구사항을 더 자세히 알려줘.,봉화군 재난통합관리시스템 고도화 주요 요구사항 상세: 시스템 기능·연계 범위·기술 ...,심화 답변: 봉화군 재난통합관리시스템 사업의 주요 요구사항은 (1) 재난통합관리시스...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
31,Q32,후속,고려대학교 사업 예산이 112억이라고 했는데 정말 맞아? 다시 확인해줘.,"112억 7천만 원(11,270,000,000원) 맞음 — 문서 재확인 결과 동일,...","1. 답변: 예, 고려대학교 사업 예산은 112.7억원(11,270,000,000원...","{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
32,Q33,종합,"스포츠윤리센터 LMS 기능개선 사업과 KUSF 체육특기자 경기기록 관리시스템 개발,...","스포츠윤리센터 LMS: 46,445,000원, 2024-08-22 / KUSF: (...","KUSF 체육특기자 경기기록 관리시스템 개발의 발주기관·예산·입찰마감일은 각각 ""(...","{'relevance': 0.5, 'faithfulness': 0.25, 'corr..."
33,Q34,종합,국방과학연구소 대용량 자료전송시스템 고도화 사업에 입찰하려면 어떤 전략을 세워야 할까?,보안 요구사항 대응 역량·대용량 전송 기술 실적 강조; 리스크 매트릭스 기반 전략 ...,핵심 전략 방향: 제안서는 '보안 준수와 성능(대용량 전송·동시접속) 확보'를 최우...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
34,Q35,종합,전기안전 관제시스템 보안 모듈 개발 용역에 참가하기 위해 준비해야 할 것들을 체크리...,"참가 자격 서류, 기술 제안서, 보안 요구사항 대응 방안, 수행 실적 증빙 등 — ...",아래는 제공된 제안요청서 문서들을 근거로 작성한 참가 준비 체크리스트입니다.\n\n...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
35,Q36,다문서추천,"교육기관이 발주한 사업들 중에서, ERP·학사 시스템 구축 경험이 있고 SI 실적 ...","고려대학교 차세대 포털(112억, 대형·ERP 역량 필수), 한국사학진흥재단 대학재...","해당 정보를 문서에서 확인할 수 없습니다. 제공된 문서 목록에 ""검색된 문서가 없습...","{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."
36,Q37,다문서추천,재난·안전 분야 사업 중 예산이 1억 원 이상인 것들의 참가 적합성을 항목별로 평가...,"봉화군 재난통합관리시스템(9억, 규모 대·요건 엄격), 전기안전 관제시스템 보안모듈...",1. 종합 판정: 조건부 GO (문서에 사업 예산·기간·기술요구 일부만 명시되어 있...,"{'relevance': 0.75, 'faithfulness': 0.75, 'cor..."
37,Q38,다문서추천,보안 인증(ISMS 또는 CC인증)이 없는 업체가 참가 불가능한 사업을 모두 식별하...,보안 인증 요건이 명시된 사업은 전기안전 관제시스템 보안모듈·국방과학연구소 등; 인...,해당 문서들에서 ISMS 또는 CC 인증이 없는 업체가 참가 불가능한 사업은 확인되...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
38,Q39,다문서추천,"예산 5억 원 미만 사업들 중에서, 공동수급 없이 단독 수행이 가능한 조합을 추천해줘.","예산 5억 미만 대상: 한영대(1.3억), 전기안전보안모듈(2.2억), 인천광역시(...",1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'relevance': 0.0, 'faithfulness': 1.0, 'corre..."
39,Q40,다문서추천,제공된 모든 사업 중에서 수익성(예산 대비 요구사항 복잡도)이 가장 유리한 사업 상...,"수익성 상위 후보: GIS 재난안전데이터(1억, 요구항목 적음), 스포츠윤리센터 L...","1) 추천 상위: 1) 예약발매시스템 개량 ISMP 용역(한국철도공사), 2) EI...","{'relevance': 0.5, 'faithfulness': 1.0, 'corre..."
40,Q41,인사이트,"제공된 공공입찰 사업들을 분야별로 분류하고, 어느 분야가 가장 활발하며 발주 규모가...","교육(고려대·한영대·한국사학진흥재단), 재난·안전(봉화군·GIS충북·전기안전), 스...","가장 활발한 분야는 IT·시스템 구축·운영 분야이며, 발주 규모가 가장 큰 사업은 ...","{'relevance': 0.5, 'faithfulness': 0.25, 'corr..."
41,Q42,인사이트,"재난관리·안전 분야 사업들을 종합해서, 발주기관들이 공통으로 요구하는 기술 역량과 ...","공통 기술 역량: GIS 연계, 실시간 데이터 수집·분석, 보안 요구 대응; 공통 ...",결론: 제공된 문서들에 따르면 발주기관들은 재난통합관리시스템의 안정적 운영·통합 데...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
42,Q43,인사이트,"학사·교육행정 시스템 관련 사업들에서, 각 발주기관이 현재 어떤 문제를 겪고 있으며...",공통 문제: 레거시 시스템 한계(확장성 부족·유지보수 비용 증가); 공통 해결 목표...,결론: 고려대학교는 기존 PC중심 포털과 분산된 모바일(호잇) 앱으로 인한 사용성·...,"{'relevance': 1.0, 'faithfulness': 1.0, 'corre..."
43,Q44,인사이트,"스포츠·체육 분야 사업들에서, 각 시스템이 해결하려는 실질적 문제와 도입 배경을 비...",KUSF 경기기록 관리: 체육특기자 입시 공정성 확보를 위한 기록 표준화·투명화가 ...,1. 확인 결과: 해당 정보를 문서에서 확인할 수 없습니다.\n\n2. 이유: 제공...,"{'relevance': 0.0, 'faithfulness': 1.0, 'corre..."
44,Q45,인사이트,2024년 하반기(7~12월)에 공고된 IT 인프라 고도화 성격의 사업들을 식별하고...,"해당 시기 공고 사업: 한국연구재단 UICC(10월), 국방과학연구소 자료전송(8월...",해당 문서들에서는 2024년 하반기(7~12월)에 공고된 IT 인프라 고도화 사업을...,"{'relevance': 0.5, 'faithfulness': 1.0, 'corre..."
45,Q46,인사이트,제공된 사업들 중 '기존 시스템 유지보수·연계'가 핵심 요구사항에 포함된 사업들을 ...,"레거시 연계가 명시된 사업: 고려대 포털(기존 학사DB 마이그레이션), 한국수자원공...",1) 답변: 제공된 문서 중 '기존 시스템 유지보수·연계'가 핵심 요구사항에 포함된...,"{'relevance': 0.75, 'faithfulness': 0.75, 'cor..."
46,Q47,인사이트,"국방·공공안전 분야(국방과학연구소, 전기안전, 봉화군 재난시스템)와 민간 교육 분야...","국방·공공안전: 높은 보안 등급 요구(CC인증·ISMS 가능성), 폐쇄망 운영 요건...",1. 확인 결과: 해당 질문은 제공된 RFP 문서의 범위를 벗어납니다.\n\n2. ...,"{'relevance': 0.25, 'faithfulness': 1.0, 'corr..."

In [17]:
for i in df_a['answer']:
    with open("result.txt", "a", encoding="utf-8") as f:
        f.write(i + df_a[df_a['answer'] == i]['category'].iloc[0] + "\n" 
                + " ".join([f"{k}:{v}" for k, v in df_a[df_a['answer'] == i]['evaluation'].iloc[0].items()]) + "\n")

In [13]:
[f"{k}:{v}" for k, v in df_a[df_a['answer'] == i]['evaluation'].iloc[0].items()]

['relevance:1.0',
 'faithfulness:1.0',
 'correctness:1.0',
 'completeness:1.0',
 'context_precision:1.0',
 'context_recall:1.0',
 'reason:답변이 질문에 정확히 응답하고(11,270,000,000원 = 112.7억원), 제시된 검색 컨텍스트와 일치해 충실·정확하며 필요한 정보(금액·부가세 표기·출처)를 모두 포함하므로 모든 항목에서 최고점을 부여합니다.']

In [165]:
import pandas as pd

# 1) evaluation에서 reason 제외하고 숫자 dict만 남기기
def drop_reason(d: dict) -> dict:
    if isinstance(d, dict):
        return {k: v for k, v in d.items() if k != "reason"}
    return d

df_a["eval_no_reason"] = df_a["evaluation"].apply(drop_reason)

# 2) dict를 여러 컬럼으로 펼치기
eval_df = pd.json_normalize(df_a["eval_no_reason"])
# 예: columns = ['relevance', 'faithfulness', 'correctness', 'completeness',
#                'context_precision', 'context_recall']

In [166]:
eval_df

,relevance,faithfulness,correctness,completeness,context_precision,context_recall
0,1.0,1.00,1.0,1.00,1.0,1.00
1,1.0,1.00,1.0,1.00,1.0,1.00
2,1.0,1.00,1.0,1.00,1.0,1.00
3,0.5,0.75,0.5,0.25,0.5,0.25
4,1.0,1.00,1.0,1.00,1.0,1.00
5,0.0,1.00,0.0,0.00,0.0,0.00
6,1.0,1.00,1.0,1.00,1.0,1.00

In [167]:
# 3) 원본 df와 합치기
df_eval = pd.concat([df_a[["category"]], eval_df], axis=1)

# 4) category별 평균
category_mean = df_eval.groupby("category").mean(numeric_only=True)
df_b = pd.DataFrame(category_mean)
df_b

,relevance,faithfulness,correctness,completeness,context_precision,context_recall
category,,,,,,
fact,0.785714,0.964286,0.785714,0.75,0.785714,0.75

In [168]:
df_b.to_csv("retrieval_experiments_summary2.csv", index=True, index_label="category")

In [169]:
df_v = pd.read_csv("retrieval_experiments_summary1.csv")

In [170]:
df_v

,category,relevance,faithfulness,correctness,completeness,context_precision,context_recall
0,fact,0.857143,1.0,0.785714,0.75,0.821429,0.75

In [171]:
df_s = pd.read_csv("retrieval_experiments_summary2.csv")
df_s

,category,relevance,faithfulness,correctness,completeness,context_precision,context_recall
0,fact,0.785714,0.964286,0.785714,0.75,0.785714,0.75

In [172]:
df_s.drop(columns=['category'], inplace=True)
df_v.drop(columns=['category'], inplace=True)

In [173]:
df_s - df_v

,relevance,faithfulness,correctness,completeness,context_precision,context_recall
0,-0.071429,-0.035714,0.0,0.0,-0.035714,0.0